### PR TITLE
Add Model Association to Plant and User model

### LINKED ISSUE #1: Add Model associations to Plant and User model
This will ensure that when creating a plant object, it carries an association of the current_user id. This is predicated on the fact that only a signed in user can create plants. If a user is not signed in, the application redirects the user to the signed in page.

### PR DESCRIPTION
**Pull request by uzorjchibuzor**
Resolves #1

### CODE REVIEW

**Comment by uzorjchibuzor** [comment]
This PR is not ready. I am trying to debug as we do not have tests yet.

**Comment by uzorjchibuzor** [comment]
PR is ready for review, while we still do not have tests yet, I ran some debugging. The next step from here is to activate the button that will add the plants into the garden.

**Comment by czepesch** [comment]
Can we have some easier name for that model? Like **profile** or **garden**? Plants are all over the place, so **garden_plant** a bit confusing 😺

**Comment by uzorjchibuzor** [comment]
> Can we have some simpler name for that model? Like **profile** or **garden**? Plants are all over the place, so **garden_plant** a bit confusing 😺

The garden_plant table is just a join table. I did not want it to say has_many :gardens,

**Pull request closed without merging**
